# Generated by Django 4.2.16 on 2026-07-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='express_attempts_left',
            field=models.PositiveIntegerField(default=0, verbose_name='Экспресс-оценок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attempts_left',
            field=models.PositiveIntegerField(default=0, verbose_name='Анализов с индикатором'),
        ),
    ]
