# Generated by Django 4.2.16 on 2026-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('score', models.FloatField(blank=True, null=True)),
                ('fresh_plaque_percent', models.FloatField(blank=True, null=True)),
                ('old_plaque_percent', models.FloatField(blank=True, null=True)),
                ('problem_zones', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('dynamics_text', models.TextField(blank=True)),
                ('doctor_comment', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('attempt_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'ordering': ['-created_at'],
            },
        ),
    ]
