# Generated by Django 4.2.16 on 2026-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_age_groups_consent_multiphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='photos_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
