# Generated by Django 4.2.16 on 2026-06-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_photos_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='prompt_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
