# Generated by Django 4.2.16 on 2026-06-11 15:38

import apps.analysis.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_add_prompt_hash_to_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='photo_url',
            field=models.ImageField(blank=True, storage=apps.analysis.storages.photo_storage, upload_to='photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='analysisphoto',
            name='photo',
            field=models.ImageField(storage=apps.analysis.storages.photo_storage, upload_to='photos/%Y/%m/'),
        ),
    ]
