# Generated by Django 4.2.16 on 2026-07-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_analysis_photo_url_alter_analysisphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='kind',
            field=models.CharField(choices=[('indicator', 'Анализ с индикатором'), ('express', 'Экспресс-оценка')], db_index=True, default='indicator', max_length=20, verbose_name='Тип анализа'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='observations',
            field=models.JSONField(blank=True, default=list, verbose_name='Наблюдения (экспресс-оценка)'),
        ),
    ]
